/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Auth: typeof import('./src/components/layout/Auth.vue')['default']
    Default: typeof import('./src/components/layout/Default.vue')['default']
    FilePreviewDialog: typeof import('./src/components/common/FilePreviewDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./src/components/common/Snackbar.vue')['default']
  }
}
